### PR TITLE
make compatible with python 3

### PR DESCRIPTION
**Pull request by mrosseel**
conversion from python 2 to python 3 (because the rest of my tools are in python 3, didn't want to go back)
- did conversion with 2to3
- fixed pickle issue by adding encoding='latin1'
- restricted scilearn to version 0.17 because the checked-in tree classifier is incompatible with the 0.18 version

### CODE REVIEW

**Comment by dwkim78** [comment]
Hi Mrosseel,

Thanks for modifying the codes for Python 3. 

Nevertheless, I'd like to keep this repository in Python 2 since there are (still) many Python 2 users. I'll probably release your modification to the new repository (e.g. something like upsilon-py3) but I don't know how to do it now. I'll try to figure it out somtime soon. Just in case you know how to do it, please let me know.

**Comment by mrosseel** [comment]
Hi dwkim,

If you make a new repository I can add my pull request to that repository.
Another option is maintaining the python3 conversion in a branch.

I think the most important thing is that people can install upsilon using PIP for either python2 or python3. Not familiar with the pip ecosystem so no idea how to do that.

**Comment by dwkim78** [comment]
Hi Mike,

I created a new repository:
https://github.com/dwkim78/py3-upsilon

I think separating repositories for Python 2 and 3 is better than maintaining a branch. Could you add your pull request again at the new repository? I'll then merge it and modify the README.md accordingly.

Cheers,

FYI. Sorry for the late response. I just started a new job, and I don't have a proper machine to work yet.

**Comment by mrosseel** [comment]
Hi,

Also sorry for the late response :). Was planning to make the pull request for the new python3 repo but it seems you already did this? Let me know, if so we can close this pull request!

**Comment by dwkim78** [comment]
Hi,

Yes, I did it based on your code :) When it's ready I'll combine Python2
and Python3 version into one repository (maybe sometime this year?)

Thank you very much for your help.

Cheers,

Dae-Won

**Comment by dwkim78** [comment]
I merged your changes  and also made a few other changes to make UPSILoN compatible with Python 3. The latest version of UPSILoN should work for both Python 2 and 3.

Thanks for your help!

Best,

Dae-Won

**Pull request closed without merging**
